# Generated by Django 5.2.3 on 2025-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_date_added_telegramuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
